.export-ci:
  stage: export-ci
  image: docker:stable
  tags:
    - docker-aarch64
  variables:
    MACHINE: raspberrypi3
    REGISTRY: $CI_REGISTRY
    REGISTRY_USER: gitlab-ci-token
    REGISTRY_PASSWORD: $CI_JOB_TOKEN
    REGISTRY_PATH: $CI_PROJECT_PATH
  script:
    - apk update
    - apk add git bash linux-headers python3 make g++ npm
    - npm install balena-cli --global --production --unsafe-perm
    - bash ./push.sh

export-ci-balena-weston-raspberrypi3:
  image: arm32v7/docker:stable
  extends:
    - .export-ci
  variables:
    MACHINE: raspberrypi3
    ARCH: armv7hf
  dependencies:
    - build-balena-weston-raspberrypi3
  needs: ["build-balena-weston-raspberrypi3"]

export-ci-balena-weston-raspberrypi3-64:
  extends:
    - .export-ci
  variables:
    MACHINE: raspberrypi3-64
  dependencies:
    - build-balena-weston-raspberrypi3-64
  needs: ["build-balena-weston-raspberrypi3-64"]

export-ci-balena-weston-raspberrypi4:
  image: arm32v7/docker:stable
  extends:
    - .export-ci
  variables:
    MACHINE: raspberrypi4
    ARCH: armv7hf
  dependencies:
    - build-balena-weston-raspberrypi4
  needs: ["build-balena-weston-raspberrypi4"]

export-ci-balena-weston-raspberrypi4-64:
  extends:
    - .export-ci
  variables:
    MACHINE: raspberrypi4-64
  dependencies:
    - build-balena-weston-raspberrypi4-64
  needs: ["build-balena-weston-raspberrypi4-64"]

