.export-prod:
  extends:
    - .prod
  stage: export-prod
  image: docker:stable
  tags:
    - docker-aarch64
  variables:
    IMAGE: balena-weston
    MACHINE: raspberrypi3
    REGISTRY: $DOCKER_HUB_REGISTRY
    REGISTRY_USER: $DOCKER_HUB_USER
    REGISTRY_PASSWORD: $DOCKER_HUB_PASSWORD
    REGISTRY_PATH: igalia
  script:
    - apk update
    - apk add git bash
    - bash ./import.sh
    - bash ./push.sh

export-prod-balena-weston-raspberrypi3:
  image: arm32v7/docker:stable
  extends:
    - .export-prod
  variables:
    MACHINE: raspberrypi3
    ARCH: arm32v7
  dependencies:
    - build-balena-weston-raspberrypi3

export-prod-balena-weston-raspberrypi3-64:
  extends:
    - .export-prod
  variables:
    MACHINE: raspberrypi3-64
  dependencies:
    - build-balena-weston-raspberrypi3-64

export-prod-balena-weston-raspberrypi4:
  image: arm32v7/docker:stable
  extends:
    - .export-prod
  variables:
    MACHINE: raspberrypi4
    ARCH: arm32v7
  dependencies:
    - build-balena-weston-raspberrypi4

export-prod-balena-weston-raspberrypi4-64:
  extends:
    - .export-prod
  variables:
    MACHINE: raspberrypi4-64
  dependencies:
    - build-balena-weston-raspberrypi4-64

